site_name: "Burak's Notes"
site_author: "Burak Rustemogullari"
site_url: https://burakrstem.github.io/docs/
docs_dir: docs


theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  language: en
  features:
    - content.code.copy
    - search.highlight
    - search.share
    - content.tabs.link
    - toc.integrate
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - scheme: slate
      primary: grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: JetBrains Mono

extra:
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
  - assets/stylesheets/extra.css


plugins:
  - awesome-pages
  - exclude:
      regex:
        - ^(?!(.*/)?assets/).*\.(?!(.*\.)?md|(.*\.)?svg|(.*\.)?png|(.*\.)?gif|(.*\.)?jpg).*$
        - ^(.*/)?[^.]*$
  - macros
  - mkdocs-video
  - same-dir
  - search
  - include-markdown

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      use_pygments: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 3


nav:
  - Home: index.md
  # - Robotics:
  #     - Intro: robotics/intro.md
  # - Embedded:
  #     - Intro: embedded/intro.md
  - C:
      - Programming and C: c/1_programming_and_c.md
      - Number Systems: c/2_number_systems.md
      - General Concepts and Terms: c/3_general_concepts_and_terms.md
      - Creating a C Program: c/4_creating_a_c_program.md
      - Data Types: c/5_data_types.md
      - Declarations and Definitions: c/6_declarations_and_definitions.md
      - Constants: c/7_constants.md
      - Operators: c/8_operators.md
      - Functions: c/9_functions.md
      - Scope and Lifetime: c/10_scope_and_lifetime.md
      - Control Statements: c/11_control_statements.md
      - If Statement: c/12_if_statement.md
      - Function Declarations: c/13_function_declarations.md
      - Type Conversions: c/14_type_conversions.md
      - Loop Statements: c/15_loop_statements.md
      - Ternary Operator: c/16_ternary_operator.md
      - Preprocessor Directives - 1: c/17_preprocessor_directives__1.md
      - Switch Statement: c/18_switch_statement.md
      - goto Statement: c/19_goto_statement.md
      - Random Number Generation and Control Statements: c/20_random_number_generation_and_control_statements.md
      - Arrays: c/21_arrays.md
      - Character Arrays and Strings: c/22_character_arrays_and_strings.md
      - sizeof Operator: c/23_sizeof_operator.md
      # - Pointers: c/24_pointers.md
      # - Pointer Operators: c/25_pointer_operators.md
      # - Standard Functions for String Operations: c/26_standard_functions_for_string_operations.md
      # - Pointer Errors: c/27_pointer_errors.md
      # - void Type Pointers: c/28_void_type_pointers.md
      # - Strings: c/29_strings.md
      # - Pointer Arrays: c/30_pointer_arrays.md
      # - Pointers to Pointers: c/31_pointers_to_pointers.md
      # - Multidimensional Arrays: c/32_multidimensional_arrays.md
      # - exit, abort and atexit Functions: c/33_exit_abort_and_atexit_functions.md
      # - Dynamic Memory Management: c/34_dynamic_memory_management.md
      # - Storage Class Specifiers and Type Qualifiers: c/35_storage_class_specifiers_and_type_qualifiers.md
      # - Structures: c/36_structures.md
      # - Type Definitions and typedef: c/37_type_definitions_and_typedef.md
      # - Date and Time Standard Functions: c/38_date_and_time_standard_functions.md
      # - Unions: c/39_unions.md
      # - Enumerations: c/40_enumerations.md
      # - Bitwise Operators: c/41_bitwise_operators.md
      # - Bit Fields: c/42_bit_fields.md
      # - Command Line Arguments: c/43_command_line_arguments.md
      # - Files: c/44_files.md
      # - Macros: c/45_macros.md
      # - Preprocessor Directives - 2: c/46_preprocessor_directives__2.md
      # - Function Pointers: c/47_function_pointers.md
      # - Recursive Functions: c/48_recursive_functions.md
      # - Variable Argument Functions: c/49_variable_argument_functions.md
      # - DSA in C: c/50_DSA_in_C.md
  # - C++:
  #     - basics: cpp/basics.md
